### ISSUE TITLE
Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer

### ISSUE THREAD

**Issue by duncannz** [fippo/webrtc-dump-importer#21]
When I import a file that I have just captured (in Chrome version 129.0.6668.60), I get the following error:

```
Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (<anonymous>)
    at new BitstreamReader (bitstream.js:19:21)
    at new BlobDecoder (bitstream.js:134:23)
    at decodeRtcpDelta (import.js:479:18)
    at Array.map (<anonymous>)
    at decode (import.js:562:10)
    at FileReader.<anonymous> (import.js:36:13)
```

**Comment by duncannz** [comment]
It appears that `buffer.data` is undefined just the last time:

<img width="708" alt="Screenshot 2024-09-27 at 2 07 59 PM" src="https://github.com/user-attachments/assets/8dd8533a-1d83-42f7-9d21-b7ae11fca54b">

I seemed to be able to work around the issue by adding

```
        if (data.buffer == null) {
            return;
        }
```

after `bitstream.js:18` (at the start of the `BitstreamReader` constructor), but I'm sure there would be a cleaner solution.

**Comment by fippo** [comment]
Should this have been in https://github.com/fippo/dump-webrtc-event-log?
Works for me with Edge's M129 format, can you share the dump?
